name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Create SQLite Database File
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Configure Database
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "APP_ENV=testing" >> .env

      - name: Generate Application Key
        run: php artisan key:generate --no-interaction

      - name: Run Migrations
        run: |
          php artisan migrate:fresh --force
          php artisan db:seed --force

      - name: Build Assets
        run: npm run build

      - name: Run Pest Tests
        run: ./vendor/bin/pest --test

      - name: Analyze Code with PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Check Code with Rector
        run: ./vendor/bin/rector --dry-run
